name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.1
  go_router: ^14.2.3
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  dio: ^5.8.0+1
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  path_provider: ^2.1.4
  shimmer: ^3.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
   

  flutter_lints: ^2.0.0
  freezed: ^2.5.2
  build_runner: ^2.4.9
  test: ^1.24.9
  mockito: ^5.4.4

flutter:

  uses-material-design: true

  fonts:
    - family: IRANSansWeb
      fonts:
        - asset: assets/fonts/IRANSansWeb_Medium.ttf
          weight: 500
        - asset: assets/fonts/IRANSansWeb_Bold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
